### ISSUE TITLE
Copy menu item to clipboard does not work in Firefox

### ISSUE THREAD

**Issue by despecial** [frederfred/fontanello#12] opened 2020-07-09 09:19 UTC
Nothing much to add. Would be useful to copy the selected item.
E.g. the color hex code, font name, etc.

**Comment by frederfred** [comment] 2020-07-09 09:30
This feature is already there: get the value in the clipboard by clicking the item.

**Comment by despecial** [comment] 2020-07-09 09:30
not working in Firefox 78

**Comment by frederfred** [comment] 2020-07-09 09:32
Ok. I’ll take a look.

**Comment by Coder417** [comment] 2020-07-11 09:39
I used to click the context menu, to have the actual font name then google it etc.. 

I confirm that this its stopped working in the most recent Firefox updates (i think starting v.76)... 

I'm on 78.0.2 (64-bit) ... copy to clipboard is not working at this version.

Thanks @frederfred

**Comment by frederfred** [comment] 2020-07-11 12:03
I have confirmed the issue and will try to fix it once I’ll find time. I updated the issue title and labeled it as a bug.

The following warning is outputted to the console:
`document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.`

Relevant docs: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

Thanks for the reports!

**Comment by despecial** [comment] 2020-11-17 10:55
No pressure but any idea when you add the fix?
Your link provides the solution. Would be nice if you could change this for Firefox users. Thx.

**Comment by Coder417** [comment] 2020-11-17 16:12
I would second that! 👍 
The extension works well in chrome... but only this feature is missing in firefox... the thing is, I still can't switch to chrome yet! :)

**Comment by frederfred** [comment] 2020-11-17 20:39
Sorry for all the delay. I have not forgot about this but also had other priorities.

I actually fixed the code in July (now with a PR: https://github.com/frederfred/fontanello/pull/13) but the thing that has stopped me from releasing this is that I don't know what happens to all current installs when I change the permissions, and I have found no good documentation about it. Will do some research!

Glad that you poked me about this one :)

**Comment by frederfred** [comment] 2020-11-26 15:24
I have now looked into this, and I'm sorry to say that I won't fix this for Firefox.

After some research and some testing, this is my reasoning:

1. The main reason to not simply add `clipboardWrite` to the permission list is that I don't want to push an update that will disable this plugin for 20 000+ users in Chrome, that would fix this for "only" 2 000+ Firefox users
  According to https://developer.chrome.com/apps/permission_warnings#update_permissions :
  > Updating an extension with additional permissions may temporarily disable it. The user will have to re-enable it after agreeing to any new warnings.
2. I don't want to fix this by adding this permission in Firefox alone because I don't want to manage multiple builds.
3. I thought I would be able to fix this by adding the permission as optional [and request it when a user clicked a context menu item](https://developer.chrome.com/apps/permission_warnings#optional_events), but this trigger `Error: permissions.request may only be called from a user input handler`. I guess the permissions api is meant to be used in the client script, but the click handler for the context menu is setup in the background script.
4. I also had an idea that I would add this as an optional permission and that Firefox users would be able to [manage it themselves through the settings page of the add on](https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions#w_view-and-manage-optional-extension-permissions), but things seems to have changed since that article was written because I can't see those toggles when trying it out.

If the plugin is developed further that requires new permissions, then I'll also add the `clipboardWrite` permission, but for now I don't think it's worth it. Sorry 🙁

If you have any other ideas, or know how to fix 3 or 4 above, please let me know!

**Comment by despecial** [comment] 2020-11-26 15:48
Too bad, I understand the pain for an obvious simple fix.

I thought about 3 and how I would "hack" it. On click, create an invisible element with a input field, put the value inside and copy it to the clipboard. Not sure if that is possible - I use it daily when developing websites that offer copy-to-clipboard links

**Comment by frederfred** [comment] 2020-11-26 18:27
> Too bad, I understand the pain for an obvious simple fix.

Yeah, too bad the permissions wasn't setup correctly in the first place :(

> I thought about 3 and how I would "hack" it. On click, create an invisible element with a input field, put the value inside and copy it to the clipboard. Not sure if that is possible - I use it daily when developing websites that offer copy-to-clipboard links

That's how it's implemented: https://github.com/frederfred/fontanello/blob/master/src/background.js#L30-L42

**Comment by despecial** [comment] 2020-11-26 21:49
Woah, 3 years ago already: https://bugzilla.mozilla.org/show_bug.cgi?id=1397658

And here is something interesting, too:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

```
Firefox:
You can write to the clipboard with execCommand in all execution contexts except background pages. In Firefox you can't select text or focus an input field in background pages, so you can't write to the clipboard with execCommand from a background page. The Clipboard Web API doesn't have this limitation.
```

```
In Chrome:
You can write to the clipboard like this in all execution contexts - background pages, content scripts, options pages, and popups.
```

**Comment by frederfred** [comment] 2020-11-26 23:21
Yeah I also did see that note about `document.execCommand` not working in background pages, but according to my tests, the copying problem in Firefox was resolved by adding the `clipboardWrite` permission.

Another thing I noticed is that the Clipboard API does not work in Chrome when used in the background, even if the `clipboardWrite` permission is added. That raises the error `Uncaught (in promise) DOMException: Document is not focused.`. Using the Clipboard API works in Firefox though (with permission added in manifest).

I also found that bug report you referenced while is was researching this. Let's hope that it will get fixed some day :)

I'll close this issue now and I might revisit it some day to see if things changed, or if the Firefox extension gets much more traction. Thanks for engaging in it!

**Closed by frederfred** 2020-11-26 23:21 UTC
Labels: bug
